### ISSUE TITLE
Missing error/warning notification in .lity file

### ISSUE THREAD

**Issue by shenzhun** [CyberMiles/remix-ide#1]
Date: 2018-12-09 15:00 PM around (Beijing Time)

os: macos 10.14.2
chrome: Version 70.0.3538.110 (Official Build) (64-bit)
Lity compiler: 1.2.4+commit.64034966.Emscripten.clang

Case:
When I created a new .lity file(https://github.com/CyberMiles/education/blob/master/meetups/beijing/3-erc20/erc20_token.lity) and miss input the ";" at the first line ```pragma lity ^1.2.4```. There was no error message at all. 

After I changeed the erc20_toekn.lity to erc20_token.sol, the error message appeared. It looks like the checker only checked the .sol file.

**Comment by dm4** [comment]
Fixed in commit 9d3024e3578651ed4fc3870b8b501a46aede9e07
