### ISSUE TITLE
safeuint is not highlighted in Remix

### ISSUE THREAD

**Issue by shenzhun** [CyberMiles/remix-ide#2]
Date: 2018-12-09 15:00 PM around (Beijing Time)

**Environment**
os: macos 10.14.2
chrome: Version 70.0.3538.110 (Official Build) (64-bit)
Lity compiler: 1.2.4+commit.64034966.Emscripten.clang

**Bug**
safeuint is a built-in data type in lity, but when I wrote my smart contract in lity, the safeuint is not highlighted in Remix IDE. Check the screenshot below:

![remix_for_cmt_-_lity_ide](https://user-images.githubusercontent.com/2031569/49845683-aff10c80-fe02-11e8-841c-ec03503eaeff.png)

**Comment by 0yi0** [comment]
We're working on syntax highlighting for the below list of keywords.

- eni
- factDelete
- factInsert
- fireAllRules
- isValidator
- rule
- safeuint
- schedule
- then
- update
- when

Thank you for reporting this issue!
